# Generated by Django 4.1 on 2024-02-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Performance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Log名称"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="关键词"
                    ),
                ),
                ("log", models.FileField(upload_to="logs/", verbose_name="Log")),
                ("del_flag", models.SmallIntegerField(default=1, verbose_name="删除标志")),
                (
                    "test_script_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Performance.case",
                        verbose_name="脚本标识",
                    ),
                ),
            ],
        ),
    ]
