# Generated by Django 4.1 on 2024-02-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Performance", "0002_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetestresults",
            name="log",
            field=models.FileField(
                blank=True, null=True, upload_to="logs/", verbose_name="Log"
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="test_script_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Performance.case",
                verbose_name="用例标识",
            ),
        ),
    ]
